import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'functions.QRscanner' :'QR Scanner',
          'auth.signInButton': 'Sign In',
          'auth.signUpButton': 'Sign Up',
          'auth.resetPasswordButton': 'Send Password Reset',
          'auth.emailFormField': 'Email',
          'auth.passwordFormField': 'Password',
          'auth.nameFormField': 'Name',
          'auth.signInErrorTitle': 'Sign In Error',
          'auth.signInError': 'Login failed: email or password incorrect.',
          'auth.resetPasswordLabelButton': 'Forgot password?',
          'auth.signUpLabelButton': 'Create an Account',
          'auth.signUpErrorTitle': 'Sign Up Failed.',
          'auth.signUpError':
              'There was a problem signing up.  Please try again later.',
          'auth.signInLabelButton': 'Have an Account? Sign In.',
          'auth.resetPasswordNoticeTitle': 'Password Reset Email Sent',
          'auth.resetPasswordNotice':
              'Check your email and follow the instructions to reset your password.',
          'auth.resetPasswordFailed': 'Password Reset Email Failed',
          'auth.signInonResetPasswordLabelButton': 'Sign In',
          'auth.updateUser': 'Update Profile',
          'auth.updateUserSuccessNoticeTitle': 'User Updated',
          'auth.updateUserSuccessNotice':
              'User information successfully updated.',
          'auth.updateUserEmailInUse':
              'That email address already has an account.',
          'auth.updateUserFailNotice': 'Failed to update user',
          'auth.enterPassword': 'Enter your password',
          'auth.cancel': 'Cancel',
          'auth.submit': 'Submit',
          'auth.changePasswordLabelButton': 'Change Password',
          'auth.resetPasswordTitle': 'Reset Password',
          'auth.updateProfileTitle': 'Update Profile',
          'auth.wrongPasswordNoticeTitle': 'Login Failed',
          'auth.wrongPasswordNotice':
              'The password does not match our records.',
          'auth.unknownError': 'Unknown Error',
          'settings.title': 'Settings',
          'settings.language': 'Language',
          'settings.theme': 'Theme',
          'settings.signOut': 'Sign Out',
          'settings.dark': 'Dark',
          'settings.light': 'Light',
          'settings.system': 'System',
          'settings.updateProfile': 'Update Profile',
          'home.title': 'Home',
          'home.nameLabel': 'Name',
          'home.uidLabel': 'UID',
          'home.emailLabel': 'Email',
          'home.adminUserLabel': 'Admin User',
          'app.title': 'Flutter Starter Project',
          'validator.email': 'Please enter a valid email address.',
          'validator.password': 'Password must be at least 6 characters.',
          'validator.name': 'Please enter a name.',
          'validator.number': 'Please enter a number.',
          'validator.notEmpty': 'This is a required field.',
          'validator.amount':
              'Please enter a number i.e. 250 - no dollar symbol and no cents',
        },
        'kz': {
          'functions.QRscanner' :'QR Scanner',
          'auth.signInButton': 'Кіру',
          'auth.signUpButton': 'Тіркелу',
          'auth.resetPasswordButton': 'Құпия сөзді қалпына келтіруді жіберу',
          'auth.emailFormField': 'Электрондық пошта',
          'auth.passwordFormField': 'Пароль',
          'auth.nameFormField': 'Аты',
          'auth.signInErrorTitle': 'Кіру сәтсіз аяқталды',
          'auth.signInError':
              'Кіру сәтсіз аяқталды: электрондық пошта немесе құпия сөз дұрыс емес.',
          'auth.resetPasswordLabelButton': 'парольді ұмыттыңыз ба?',
          'auth.signUpLabelButton': 'Тіркелгі жасау',
          'auth.signUpErrorTitle': 'Тіркеу сәтсіз аяқталды.',
          'auth.signUpError':
              'Қол қою мәселесі болды. Тағы жасауды сәл кейінірек көріңізді өтінеміз. ',
          'auth.signInLabelButton': 'Тіркелгі бар ма? Кіру.',
          'auth.resetPasswordNoticeTitle':
              'Жіберілген құпия сөзді қалпына келтіру',
          'auth.resetPasswordNotice':
              'Электрондық поштаңызды тексеріп, құпия сөзді қалпына келтіру үшін нұсқауларды орындаңыз.',
          'auth.resetPasswordFailed':
              'Құпия сөзді қалпына келтіру электрондық пошта орындалмады',
          'auth.signInonResetPasswordLabelButton': 'Кіру',
          'auth.updateUser': 'Профильді жаңарту',
          'auth.updateUserSuccessNoticeTitle': 'Пайдаланушы жаңартылды',
          'auth.updateUserSuccessNotice':
              'Пайдаланушы ақпараты сәтті жаңартылды.',
          'auth.updateUserEmailInUse':
              'Бұл электрондық пошта мекенжайында есептік жазба бар.',
          'auth.updateUserFailNotice': 'Пайдаланушыны жаңарту сәтсіз аяқталды',
          'auth.enterPassword': 'Құпия сөзіңізді енгізіңіз',
          'auth.cancel': 'Болдырмау',
          'auth.submit': 'Жіберу',
          'auth.changePasswordLabelButton': 'Құпия сөзді өзгерту',
          'auth.resetPasswordTitle': 'Құпия сөзді қалпына келтіру',
          'auth.updateProfileTitle': 'Профильді жаңарту',
          'auth.wrongPasswordNoticeTitle': 'Кіру сәтсіз аяқталды',
          'auth.wrongPasswordNotice':
              'Құпия сөз біздің деректерге сәйкес келмейді.',
          'auth.unknownError': 'Белгісіз қате',
          'settings.title': 'Параметрлер',
          'settings.language': 'Тіл',
          'settings.theme': 'Тақырып',
          'settings.signOut': 'Шығу',
          'settings.dark': 'Қараңғы',
          'settings.light': 'Жарық',
          'settings.system': 'Жүйе',
          'settings.updateProfile': 'Профильді жаңарту',
          'home.title': 'Үй',
          'home.nameLabel': 'Аты',
          'home.uidLabel': 'UID',
          'home.emailLabel': 'Электрондық пошта',
          'home.adminUserLabel': 'Әкімші пайдаланушы',
          'app.title': 'Project Flutter Starter',
          'validator.email': 'Жарамды электрондық пошта мекенжайын енгізіңіз.',
          'validator.password': 'Құпия сөз кемінде 6 таңбадан тұруы керек.',
          'validator.name': 'Атын енгізіңіз.',
          'validator.number': 'Нөмірді енгізіңіз.',
          'validator.notEmpty': 'Бұл өріс қажет.',
          'validator.amount':
              '250 нөмірін енгізіңіз, яғни. доллар белгісі жоқ және цент емес ',
        },
        'ru': {
          'functions.QRscanner' :'QR Scanner',
          'auth.signInButton': 'Войти',
          'auth.signUpButton': 'Зарегистрироваться',
          'auth.resetPasswordButton': 'Отправить Сброс пароля',
          'auth.emailFormField': 'Электронная почта',
          'auth.passwordFormField': 'Пароль',
          'auth.nameFormField': 'Имя',
          'auth.signInErrorTitle': 'Ошибка входа',
          'auth.signInError':
              'Войти не удалось: адрес электронной почты или пароль неверен.',
          'auth.resetPasswordLabelButton': 'забыл пароль?',
          'auth.signUpLabelButton': 'Завести аккаунт',
          'auth.signUpErrorTitle': 'Регистрация прошла неудачно.',
          'auth.signUpError':
              'Была проблема подписания. Пожалуйста, повторите попытку позже.',
          'auth.signInLabelButton': 'Есть аккаунт? Войдите.',
          'auth.resetPasswordNoticeTitle': 'Сброс пароля Email! Отправлено!',
          'auth.resetPasswordNotice':
              'Проверьте электронную почту и следуйте инструкциям, чтобы сбросить пароль.',
          'auth.resetPasswordFailed': 'Сброс пароля Email! Ошибка!',
          'auth.signInonResetPasswordLabelButton': 'Войти',
          'auth.updateUser': 'Обновить профиль',
          'auth.updateUserSuccessNoticeTitle': 'Профиль обновлен',
          'auth.updateUserSuccessNotice':
              'Информация о пользователе успешно обновлена.',
          'auth.updateUserEmailInUse':
              'Этот адрес электронной почты уже есть учетная запись.',
          'auth.updateUserFailNotice': 'Не удался пользователь обновления',
          'auth.enterPassword': 'Введите свой пароль',
          'auth.cancel': 'Отмена',
          'auth.submit': 'Представлять на рассмотрение',
          'auth.changePasswordLabelButton': 'Измени пароль',
          'auth.resetPasswordTitle': 'Сброс пароля',
          'auth.updateProfileTitle': 'Обновить профиль',
          'auth.wrongPasswordNoticeTitle': 'Ошибка входа',
          'auth.wrongPasswordNotice': 'Пароль не соответствует нашим данным.',
          'auth.unknownError': 'Неизвестная ошибка',
          'settings.title': 'Настройки',
          'settings.language': 'Язык',
          'settings.theme': 'Тема',
          'settings.signOut': 'Выход',
          'settings.dark': 'Темный',
          'settings.light': 'Свет',
          'settings.system': 'Система',
          'settings.updateProfile': 'Обновить профиль',
          'home.title': 'Дом',
          'home.nameLabel': 'Имя',
          'home.uidLabel': 'UID',
          'home.emailLabel': 'Электронное письмо',
          'home.adminUserLabel': 'Привелегии Admin',
          'app.title': 'Проект флаттер Starter',
          'validator.email':
              'Пожалуйста, введите действительный адрес электронной почты.',
          'validator.password': 'Пароль должен быть не менее 6 символов.',
          'validator.name': 'Пожалуйста, введите имя.',
          'validator.number': 'Пожалуйста, введите номер.',
          'validator.notEmpty': 'Это поле обязательно для заполнения.',
          'validator.amount':
              'Пожалуйста, введите номер 250 - т.е. без символа доллара и ни цента',
        },
      };
}
