name: astup
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  firebase_core: ^1.8.0
  firebase_app_check: ^0.0.2+3
  firebase_crashlytics: ^2.2.4
  cloud_firestore: ^2.5.4
  firebase_auth: ^3.1.3
  firebase_analytics: ^8.3.3
  flutter_signin_button: ^2.0.0
  flutter_form_builder: ^7.0.0
  flutter_native_splash: ^1.3.1
  scoped_model: ^1.1.0
  loading: ^1.0.2
  flutter_lock_screen: ^1.0.5
  get_storage: ^2.0.2
  crypto: ^3.0.1
  http: ^0.13.1
  csv: ^5.0.0
  colorize_text_avatar: ^1.0.2
  flutter_barcode_scanner: ^2.0.0
  fab_circular_menu: ^1.0.2
  qr_code_scanner: ^0.5.2
  quick_actions: ^0.6.0+7
  flutter_local_notifications: ^9.0.2

  #  flutter_datetime_picker: ^1.3.1
  shared_preferences: ^2.0.8
  connectivity_plus: ^2.0.2
  #  cached_network_image: ^3.1.0
  #  flutter_swiper: ^1.1.6
  #  flutter_easyrefresh: ^2.2.1
  #  get_version: ^0.2.2
  #  loading_indicator: ^3.0.2
  #  dio: ^4.0.1
  oktoast: ^3.1.3+1
  path_provider: ^2.0.6
  get: ^4.3.8
#  event_bus: ^2.0.0
  rxdart: ^0.27.2
#  rx_command: ^6.0.1
#  bloc: ^7.2.1
#  flutter_bloc: ^7.3.1
#  equatable: ^2.0.3
#  wave: ^0.2.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/astup_icon.png"
  image_path_android: "assets/icon/astup_scan.png"
  image_path_ios: "assets/icon/astup_scan.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/icon/astup_scan.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/