name: astup
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0-alpha+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.3
  firebase_core: ^1.8.0
  firebase_app_check: ^0.0.2+3
  firebase_crashlytics: ^2.2.4
  firebase_auth: ^3.1.3
  firebase_analytics: ^9.1.2
  firebase_database: ^9.0.8
  scoped_model: ^1.1.0
  loading: ^1.0.2
  get_storage: ^2.0.2
  crypto: ^3.0.1
  http: ^0.13.4
  csv: ^5.0.1
  colorize_text_avatar: ^1.0.2
  flutter_lock_screen: ^2.0.1
  flutter_barcode_scanner: ^2.0.0
  flutter_signin_button: ^2.0.0
  flutter_form_builder: ^7.0.0
  flutter_native_splash: ^2.0.5
  fab_circular_menu: ^1.0.2
  qr_code_scanner: ^0.7.0
  quick_actions: ^0.6.0+7
  flutter_local_notifications: ^9.0.2
  provider: ^6.0.1
  cached_network_image: ^3.1.0
  shared_preferences: ^2.0.8
  connectivity_plus: ^2.0.2

  oktoast: ^3.1.3+1
  path_provider: ^2.0.6
  get: ^4.3.8
  rxdart: ^0.27.2

  get_it: ^7.2.0

  platform_device_id: ^1.0.1
  timelines: ^0.1.0
  flutter_breadcrumb: ^1.0.1

  expandable_bottom_bar: ^2.0.2
  device_info_plus: ^3.1.1
  qr_mobile_vision: ^3.0.1
  package_info_plus: ^1.3.0
  about: ^2.1.1

  # flutter_debug_drawer: 





flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/astup_icon.png"
  image_path_android: "assets/icon/astup_scan.png"
  image_path_ios: "assets/icon/astup_scan.png"
  adaptive_icon_background: "#03c03c"
  adaptive_icon_foreground: "assets/icon/astup_scan.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  pubspec_extract: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - md/CHANDELOG.md
    - md/LICENSE.md
    - md/README.md